In [1]:
import requests
res = requests.get('https://news.ltn.com.tw/ajax/breakingnews/all/4')
jd = res.json()
import pandas
df = pandas.DataFrame(jd['data'].values())
import time
newsary = []
for i in range(2,5):
  res = requests.get('https://news.ltn.com.tw/ajax/breakingnews/all/{}'.format(i))
  time.sleep(2)
  #print(res.json())
  jd = res.json()
  df = pandas.DataFrame(jd['data'].values())
  newsary.append(df)

In [2]:
newsdf = pandas.concat(newsary)

In [3]:
newsdf.head()

,bigphoto_flag,group,height,local,localUrl,no,photo_L,photo_S,style,summary,tagText,tagUrl,time,title,type_cn,type_en,url,video,width
0,0,breakingnews,1168,,,3700540,https://img.ltn.com.tw/Upload/news/600/2021/10...,https://img.ltn.com.tw/Upload/news/250/2021/10...,None,高雄17歲少女小玉（化名）網路結識一名丁姓男網友，丁男已是40歲，卻用其他20歲帥男的照片，...,社會,list/breakingnews/society,17:17,17歲少女網交「20歲帥哥」離家失聯 少年隊一查已40歲...,社會,society,https://news.ltn.com.tw/news/society/breakingn...,,769
1,0,breakingnews,450,,,3700500,https://img.ltn.com.tw/Upload/ent/page/800S/20...,https://img.ltn.com.tw/Upload/ent/page/400S/20...,None,\n\n\nSandy（吳姍儒）在本屆金鐘獎奪下綜藝節目主持人獎，她在典禮所穿的禮服成為矚目...,娛樂,list/breakingnews/entertainment,17:17,Sandy金鐘典禮「露餡」遭疑有孕 親曝身體一狀況：大家放心,影劇,entertainment,https://ent.ltn.com.tw/news/breakingnews/3700500,,800
2,0,breakingnews,600,,,3700443,https://img.ltn.com.tw/Upload/news/600/2021/10...,https://img.ltn.com.tw/Upload/news/250/2021/10...,None,一名網友在社群平台分享，想要煮水餃給女友吃，但因為從未煮過水餃，前往超市買了最高級的水餃卻不...,蒐奇,list/breakingnews/novelty,17:07,他好奇水餃「最頂級煮法」 網曝妙招：用煎的再難吃都直接升級,蒐奇,novelty,https://news.ltn.com.tw/news/novelty/breakingn...,,800
3,1,breakingnews,450,,,3651133,https://img.ltn.com.tw/Upload/news/600/2021/08...,https://img.ltn.com.tw/Upload/news/250/2021/08...,None,首次上稿 08/26 14:39更新時間 10/11 17:07\n\n行政院推出「振興五倍...,生活,list/breakingnews/life,17:07,紙本五倍券10/8起領用 加碼券連抽4週、各縣市加碼內容一次看,生活,life,https://news.ltn.com.tw/news/life/breakingnews...,1,800
4,0,breakingnews,559,,,3700555,https://img.ltn.com.tw/Upload/sports/page/800S...,https://img.ltn.com.tw/Upload/sports/page/400S...,None,\n\n\n中信兄弟宣布續留洋投羅傑斯，格里斯和高野圭佑則「出局」。今天賽前聯盟官網球員異動...,體育,list/breakingnews/sports,17:06,中職》昨初登板即是最終戰 高野圭佑賽前離隊,體育,sports,https://sports.ltn.com.tw/news/breakingnews/37...,,695